// trigger: 'click' → avanza al hacer clic dentro del elemento resaltado
// trigger: 'change' → avanza al cambiar un select dentro del elemento resaltado
// trigger: null → informativo, el usuario avanza con el botón "Siguiente"
export const TUTORIAL_STEPS = [
  {
    id: 'agendar-cita-btn',
    selector: '[data-tutorial="agendar-cita-btn"]',
    title: 'Botón "Agendar Cita"',
    message: 'Haz clic en este botón para ir al formulario de registro de citas.',
    navigateTo: '/padres/agendar',
    formStep: null,
    trigger: 'click',
  },
  {
    id: 'step-indicator',
    selector: '[data-tutorial="step-indicator"]',
    title: 'Indicador de progreso',
    message: 'El formulario tiene 5 pasos. Este indicador muestra en cuál etapa te encuentras. Presiona "Siguiente" para empezar.',
    formStep: 1,
    trigger: null,
  },
  {
    id: 'children-grid',
    selector: '[data-tutorial="children-grid"]',
    title: 'Paso 1 — Selecciona al paciente',
    message: 'Haz clic en la tarjeta de tu hijo/a para seleccionarlo como paciente de la consulta.',
    formStep: 1,
    trigger: 'click',
  },
  {
    id: 'specialty-select',
    selector: '[data-tutorial="specialty-select"]',
    title: 'Paso 2 — Elige la especialidad',
    message: 'Selecciona la especialidad médica que necesitas. La lista de médicos se actualizará automáticamente.',
    formStep: 2,
    trigger: 'change',
  },
  {
    id: 'doctor-select',
    selector: '[data-tutorial="doctor-select"]',
    title: 'Paso 2 — Elige el médico',
    message: 'Elige el médico disponible dentro de la especialidad seleccionada.',
    formStep: 2,
    trigger: 'change',
  },
  {
    id: 'horarios-list',
    selector: '[data-tutorial="horarios-list"]',
    title: 'Paso 3 — Selecciona el horario',
    message: 'Haz clic en el turno disponible que mejor se adapte a tu agenda.',
    formStep: 3,
    trigger: 'click',
  },
  {
    id: 'motivo-input',
    selector: '[data-tutorial="motivo-input"]',
    title: 'Paso 3 — Motivo de consulta',
    message: 'Escribe el motivo de la consulta: síntomas, tipo de revisión, u otro detalle importante. Cuando termines, presiona "Siguiente".',
    formStep: 3,
    trigger: null,
  },
  {
    id: 'payment-methods',
    selector: '[data-tutorial="payment-methods"]',
    title: 'Paso 4 — Método de pago',
    message: 'Haz clic en tu método de pago preferido: Yape/Plin, PayPal, Tarjeta o Efectivo.',
    formStep: 4,
    trigger: 'click',
  },
  {
    id: 'comprobante-section',
    selector: '[data-tutorial="comprobante-section"]',
    title: 'Paso 4 — Tipo de comprobante',
    message: 'Selecciona Boleta (con tu DNI) o Factura (para empresas con RUC).',
    formStep: 4,
    trigger: 'click',
  },
  {
    id: 'confirm-section',
    selector: '[data-tutorial="confirm-section"]',
    title: 'Paso 5 — Confirmar tu cita',
    message: 'Revisa todos los detalles. Cuando estés listo, haz clic en "Confirmar y Agendar" para finalizar el registro de tu cita.',
    formStep: 5,
    trigger: null,
  },
];
