export const TUTORIAL_STEPS = [
  {
    id: 'agendar-cita-btn',
    selector: '[data-tutorial="agendar-cita-btn"]',
    title: 'Botón "Agendar Cita"',
    message: 'Aquí puedes acceder al formulario para registrar una nueva cita médica para tus hijos. Haz clic en este botón cuando quieras agendar una consulta.',
    navigateTo: '/padres/agendar',
    formStep: null,
  },
  {
    id: 'step-indicator',
    selector: '[data-tutorial="step-indicator"]',
    title: 'Indicador de progreso',
    message: 'El formulario de citas tiene 5 pasos. Este indicador te muestra en cuál etapa te encuentras durante el proceso de registro.',
    formStep: 1,
  },
  {
    id: 'children-grid',
    selector: '[data-tutorial="children-grid"]',
    title: 'Paso 1 — Selecciona al paciente',
    message: 'Haz clic en la tarjeta de tu hijo/a para seleccionarlo como paciente de la consulta. Solo podrás continuar si eliges a uno.',
    formStep: 1,
  },
  {
    id: 'specialty-select',
    selector: '[data-tutorial="specialty-select"]',
    title: 'Paso 2 — Elige la especialidad',
    message: 'Selecciona la especialidad médica que necesitas para la consulta: Pediatría, Cardiología, Dermatología, etc.',
    formStep: 2,
  },
  {
    id: 'doctor-select',
    selector: '[data-tutorial="doctor-select"]',
    title: 'Paso 2 — Elige el médico',
    message: 'Una vez elegida la especialidad, selecciona el médico disponible. Solo aparecerán los doctores activos para esa especialidad.',
    formStep: 2,
  },
  {
    id: 'horarios-list',
    selector: '[data-tutorial="horarios-list"]',
    title: 'Paso 3 — Selecciona el horario',
    message: 'Elige el turno disponible que mejor se adapte a tu agenda. Solo se muestran horarios futuros del médico seleccionado.',
    formStep: 3,
  },
  {
    id: 'motivo-input',
    selector: '[data-tutorial="motivo-input"]',
    title: 'Paso 3 — Motivo de consulta',
    message: 'Escribe aquí el motivo de la consulta: síntomas, tipo de revisión, o cualquier detalle importante que el médico deba saber.',
    formStep: 3,
  },
  {
    id: 'payment-methods',
    selector: '[data-tutorial="payment-methods"]',
    title: 'Paso 4 — Método de pago',
    message: 'Elige cómo deseas pagar tu consulta: Yape/Plin, PayPal, Tarjeta de crédito/débito o Efectivo en caja.',
    formStep: 4,
  },
  {
    id: 'comprobante-section',
    selector: '[data-tutorial="comprobante-section"]',
    title: 'Paso 4 — Tipo de comprobante',
    message: 'Selecciona el tipo de comprobante que deseas recibir: Boleta (con tu DNI) o Factura (para empresas, requiere RUC).',
    formStep: 4,
  },
  {
    id: 'confirm-section',
    selector: '[data-tutorial="confirm-section"]',
    title: 'Paso 5 — Confirmar tu cita',
    message: 'Revisa todos los detalles de tu cita: paciente, médico, fecha, horario y pago. Cuando estés seguro, haz clic en "Confirmar y Agendar" para finalizar el registro.',
    formStep: 5,
  },
];
