spring.application.name=backend-Medikids
server.port=8085

# ── Base de Datos ──
spring.datasource.url=jdbc:mysql://localhost:3306/medikids_db
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

# ── Mail SMTP (Gmail) ──
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=medikids.contacto@gmail.com
spring.mail.password=uxdo rliz efvb xjqu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ── JWT ──
jwt.secret=MedikidsSecretKey2026SuperSeguraParaJWTTokens1234567890ABCDEF
jwt.expiration=86400000

# ── 2FA ──
codigo.2fa.expiration=300000